version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "18:30"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      # parser shall be same version as Ruby
      - dependency-name: "parser"
