version: '3'
services:
  test_db:
    image: mysql:5.7.41
    platform: linux/x86_64
    volumes:
      - test_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  test_web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ec_rails
      - test_bundle:/usr/local/bundle
    ports:
      - "3001:3000"
    environment:
      DB_HOST: test_db
      DB_PORT: 3307
      DB_NAME: sandbox_test
      DB_USER: root
      DB_PASS: root
      RAILS_ENV: test
      GOOGLE_OAUTH2_CLIENT_ID: ''
    depends_on:
      - test_db

volumes:
  test_db_data:
  test_bundle:
