# Brakeman configuration
# Ignore Unmaintained Dependency warnings by skipping EOL checks
skip_checks:
  - CheckEOLRails
  - CheckEOLRuby

skip_lines:
  UnscopedFind:
    app/controllers/dog_supporters_controller.rb:
      - 24
